/* =========================================================
   JobReady SG — shared script
   Handles: nav active state, mobile menu,
   scroll-triggered fade-ins, demo conversation animation,
   and the architecture diagram simulation.
   Cross-page transitions are handled natively by the browser's
   View Transitions API (see @view-transition in style.css).
   The Botpress chat is a floating widget injected on every page
   (see the IIFE below) rather than a dedicated chat.html page.
   ========================================================= */

// Mark JS as available immediately so CSS only hides reveal-target
// elements when it knows the observer below will actually run.
document.documentElement.classList.add('js-ready');

/* ---------- shared auth session helpers ----------
   Used here to render nav login state, and by signup.html/login.html
   after a successful webhook call. Session is just {name, email, token} -
   there's no protected data behind it yet, so trusting localStorage is
   fine for now; a real protected endpoint would need to validate the
   token server-side, not just check that it's present client-side. */
window.jrAuth = {
  KEY: 'jobready_session',
  getSession: function () {
    try { return JSON.parse(localStorage.getItem(this.KEY)); } catch (e) { return null; }
  },
  setSession: function (session) {
    localStorage.setItem(this.KEY, JSON.stringify(session));
  },
  clearSession: function () {
    localStorage.removeItem(this.KEY);
  }
};

/* ---------- Botpress floating chat widget (loads on every page) ----------
   themeMode/botAvatar are set from the site's current theme at load time.
   Botpress doesn't reliably re-apply config via a second init() call once
   the widget is already mounted, so this only matches the theme active
   when the page loads - it won't retroactively re-skin an open widget if
   the user flips the toggle mid-session (next page load will match). */
window.jrChatTheme = {
  BOT_ID: 'da2bb2c1-4daf-4568-8593-a01282a30184',
  CLIENT_ID: '25167031-b7a3-4334-9aea-97a0ff5a63e1',
  AVATAR_URL: 'https://riflearn.github.io/jobready-sg/assets/bot-avatar.png',
  // base config mirrors the "Embed on your website" script generated by
  // the Botpress dashboard (Integration Hub -> Webchat), so dashboard
  // settings (fabImage, disabled homepage/history/sound, etc.) aren't
  // silently dropped - only themeMode/botAvatar are overridden here.
  BASE_CONFIG: {
    version: 'v2',
    fabImage: 'https://files.bpcontent.cloud/2026/07/10/13/20260710134525-7E3AZAU9.jpg',
    website: {}, email: {}, phone: {}, termsOfService: {}, privacyPolicy: {},
    color: '#3276EA',
    variant: 'solid',
    headerVariant: 'solid',
    fontFamily: 'inter',
    radius: 4,
    feedbackEnabled: false,
    footer: '[⚡ by Botpress](https://botpress.com/?from=webchat)',
    soundEnabled: false,
    proactiveMessageEnabled: false,
    proactiveBubbleMessage: 'Hi! 👋 Need help?',
    proactiveBubbleTriggerType: 'afterDelay',
    proactiveBubbleDelayTime: 10,
    conversationHistory: false,
    homePageEnabled: false,
    mainCardEnabled: false,
    conversationStartersEnabled: false,
    conversationStarters: [],
    conversationStartersDisplayStyle: 'cards'
  },
  apply: function (theme) {
    if (!window.botpress || !window.botpress.init) return;
    var config = Object.assign({}, this.BASE_CONFIG, {
      themeMode: theme === 'dark' ? 'dark' : 'light',
      botAvatar: this.AVATAR_URL
    });
    window.botpress.init({
      botId: this.BOT_ID,
      clientId: this.CLIENT_ID,
      configuration: config
    });
  }
};
(function () {
  var s = document.createElement('script');
  s.src = 'https://cdn.botpress.cloud/webchat/v3.6/inject.js';
  s.onload = function () {
    var theme = document.documentElement.getAttribute('data-theme');
    window.jrChatTheme.apply(theme);
  };
  document.head.appendChild(s);
})();

document.addEventListener('DOMContentLoaded', () => {

  /* ---------- auth state in nav (desktop + mobile) ---------- */
  (function () {
    var session = window.jrAuth.getSession();
    [document.getElementById('authArea'), document.getElementById('authAreaMobile')].forEach((el) => {
      if (!el) return;
      if (session && session.name) {
        var firstName = String(session.name).split(' ')[0]
          .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
        el.innerHTML = '<span class="auth-chip"><span class="auth-chip__name">Hi, ' + firstName + '</span>' +
          '<button class="auth-chip__logout" type="button">Log Out</button></span>';
        el.querySelector('.auth-chip__logout').addEventListener('click', () => {
          window.jrAuth.clearSession();
          window.location.reload();
        });
      } else {
        el.innerHTML = '<a href="login.html" class="auth-login-link">Log In</a>';
      }
    });
  })();

  /* ---------- highlight the active nav link ---------- */
  const page = document.body.dataset.page;
  document.querySelectorAll('.nav-links a, .mobile-panel a').forEach(link => {
    if (link.dataset.page === page) link.classList.add('active');
  });

  /* ---------- mobile menu toggle ---------- */
  const toggle = document.getElementById('navToggle');
  const panel = document.getElementById('mobilePanel');
  if (toggle && panel) {
    toggle.addEventListener('click', () => panel.classList.toggle('open'));
    panel.querySelectorAll('a').forEach(a => a.addEventListener('click', () => panel.classList.remove('open')));
  }

  /* ---------- buttons/links that open the floating Botpress widget ---------- */
  document.querySelectorAll('[data-open-chat]').forEach((el) => {
    el.addEventListener('click', (e) => {
      e.preventDefault();
      if (window.botpress && window.botpress.open) window.botpress.open();
    });
  });

  /* ---------- dark/light theme toggle ----------
     Initial theme is already applied by an inline script in <head>
     (before first paint, to avoid a flash of the wrong theme). This
     just wires up the button to flip it and remember the choice. */
  const themeToggle = document.getElementById('themeToggle');
  if (themeToggle) {
    themeToggle.addEventListener('click', () => {
      const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
      const next = isDark ? 'light' : 'dark';
      document.documentElement.setAttribute('data-theme', next);
      localStorage.setItem('theme', next);
    });
  }

  /* ---------- scroll-triggered fade-in for cards and blocks ---------- */
  const revealSelectors = [
    '.agent-card', '.jstep', '.team-card', '.tech-badge', '.faq-item',
    '.video-shell', '.arch-shell', '.chat-frame', '.convo-shell', '.block-title'
  ].join(',');
  const revealEls = document.querySelectorAll(revealSelectors);
  if (revealEls.length) {
    const revealIO = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          const el = entry.target;
          el.classList.add('in-view');
          // once the entrance animation finishes, drop it so it stops
          // overriding hover/transform interactions permanently
          el.addEventListener('animationend', () => el.classList.add('reveal-done'), { once: true });
          revealIO.unobserve(el);
        }
      });
    }, { threshold: .15, rootMargin: '0px 0px -40px 0px' });
    revealEls.forEach(el => {
      el.classList.add('reveal-target');
      revealIO.observe(el);
    });
  }

});

/* =========================================================
   DEMO PAGE: animated example conversation
   Reveals the existing static .convo-msg elements one at a
   time rather than building new markup.
   ========================================================= */
let demoTimer = null;
function playDemo() {
  const body = document.getElementById('demoBody');
  if (!body) return;
  const messages = body.querySelectorAll('.convo-msg');
  messages.forEach(m => m.classList.remove('shown'));
  clearTimeout(demoTimer);
  let i = 0;
  (function step() {
    if (i >= messages.length) return;
    messages[i].classList.add('shown');
    i++;
    demoTimer = setTimeout(step, 1100);
  })();
}
document.addEventListener('DOMContentLoaded', () => {
  const demoBody = document.getElementById('demoBody');
  if (!demoBody) return;
  const io = new IntersectionObserver((entries) => {
    entries.forEach(e => { if (e.isIntersecting) { playDemo(); io.disconnect(); } });
  }, { threshold: .4 });
  io.observe(demoBody);
});

/* =========================================================
   DEMO PAGE: architecture pipeline simulation
   ========================================================= */
function runArchDemo() {
  const order = ['1','2','3','4','4a','4b','4c','5','6'];
  const connOrder = ['1','2','3','4','5'];
  document.querySelectorAll('.arch-node, .arch-connector').forEach(n => n.classList.remove('active'));
  order.forEach((n, idx) => {
    setTimeout(() => {
      const node = document.querySelector('[data-n="' + n + '"]');
      if (node) node.classList.add('active');
      setTimeout(() => node && node.classList.remove('active'), 900);
    }, idx * 350);
  });
  connOrder.forEach((c, idx) => {
    setTimeout(() => {
      const conn = document.querySelector('[data-c="' + c + '"]');
      if (conn) conn.classList.add('active');
      setTimeout(() => conn && conn.classList.remove('active'), 900);
    }, idx * 700 + 175);
  });
}
